/*
 * Generated by inst.c 
 * This file is used to retrieve files hyaccpar and hyaccmanpage.
 * This file is updated each time hyacc is installed.
 */

#include "y.h"

void show_manpage() {
   system("less /usr/local/lib/hyacc/hyaccmanpage");
}

char * HYACC_PATH = 
  "/usr/local/lib/hyacc/hyaccpar";

