/*
 * Generated by inst.c 
 * This file is used to retrieve files hyaccpar and hyaccmanpage.
 * This file is updated each time hyacc is installed.
 */

#include "y.h"

void show_manpage() {
   system("less /home/ThomasXC/yacc3/test/tmp/hyacc_unix_src_01_27_2011/hyaccmanpage");
}

char * HYACC_PATH = 
  "/home/ThomasXC/yacc3/test/tmp/hyacc_unix_src_01_27_2011/hyaccpar";

